### ISSUE TITLE
Musl compiled Python support

### ISSUE THREAD

**Issue by mdgomes** [sharkwouter/minigalaxy#139]
Hello,

Due to musl differences to glibc handling of locales, the following python locale method functions should not be used and gettext ones should be used:

locale.gettext(msg)
locale.dgettext(domain, msg)
locale.dcgettext(domain, msg, category)
locale.textdomain(domain)
locale.bindtextdomain(domain, dir)

Otherwise the following error occurs:

```
$ minigalaxy 
Traceback (most recent call last):
  File "/usr/bin/minigalaxy", line 66, in <module>
    main()
  File "/usr/bin/minigalaxy", line 57, in main
    from minigalaxy.ui import Window
  File "/usr/lib/python3.8/site-packages/minigalaxy/ui/__init__.py", line 2, in <module>
    from minigalaxy.ui.window import Window
  File "/usr/lib/python3.8/site-packages/minigalaxy/ui/window.py", line 5, in <module>
    from minigalaxy.ui.login import Login
  File "/usr/lib/python3.8/site-packages/minigalaxy/ui/login.py", line 8, in <module>
    from minigalaxy.translation import _
  File "/usr/lib/python3.8/site-packages/minigalaxy/translation.py", line 8, in <module>
    locale.bindtextdomain(TRANSLATION_DOMAIN, LOCALE_DIR)
AttributeError: module 'locale' has no attribute 'bindtextdomain'
```
Commenting "locale.bindtextdomain(TRANSLATION_DOMAIN, LOCALE_DIR)" in minigalaxy/translation.py fixes the issues and allows minigalaxy to launch :)

This change makes it Alpine Linux (and probably other musl distros) ready :)

**Comment by sharkwouter** [comment]
That's a shame. For me when I don't use locale.bindtextdomain, the translations aren't fully loaded. I can add a small check though to make sure it doesn't crash in Alpine.

**Comment by sharkwouter** [comment]
Could you clone master and test again? I've added a workaround.

**Comment by mdgomes** [comment]
It works, many thanks :)
