### ISSUE TITLE
UI broken when no download link found

### ISSUE THREAD

**Issue by dos1** [sharkwouter/minigalaxy#145]
When trying to install Gwent, I'm getting following exception:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/minigalaxy/ui/gametile.py", line 197, in __download_file
    download_info = self.api.get_download_info(self.game)
  File "/usr/lib/python3.8/site-packages/minigalaxy/api.py", line 135, in get_download_info
    return self.get_download_info(game, "windows")
  File "/usr/lib/python3.8/site-packages/minigalaxy/api.py", line 137, in get_download_info
    raise NoDownloadLinkFound("Error: {} with id {} couldn't be installed".format(game.name, game.id))
minigalaxy.api.NoDownloadLinkFound: Error: GWENT: The Witcher Card Game with id 1971477531 couldn't be installed
```

After that happens, the button under the game image remains disabled and trying to cancel the download results in another exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/minigalaxy/ui/gametile.py", line 119, in on_button_cancel
    DownloadManager.cancel_download(self.download)
  File "/usr/lib/python3.8/site-packages/minigalaxy/download_manager.py", line 39, in cancel_download
    for download in downloads:
TypeError: 'NoneType' object is not iterable
```

Tested on 0.9.4

**Comment by sharkwouter** [comment]
Thanks for the detailed bug report, I'll take a look at it

**Comment by sharkwouter** [comment]
This will be fixed in the next release.
