### ISSUE TITLE
Crash after entering credentials

### ISSUE THREAD

**Issue by lotth** [sharkwouter/minigalaxy#157]
Minigalaxy crashes every time after I enter my credentials (email, password and, first time, two-factor 4 gidit code).
minigalaxy version 0.9.4
OS : Fedora 32 x64

Traceback (most recent call last):
  File "/usr/bin/minigalaxy", line 66, in <module>
    main()
  File "/usr/bin/minigalaxy", line 60, in main
    window = Window(APPLICATION_NAME)
  File "/usr/lib/python3.8/site-packages/minigalaxy/ui/window.py", line 51, in __init__
    self.__authenticate()
  File "/usr/lib/python3.8/site-packages/minigalaxy/ui/window.py", line 128, in __authenticate
    authenticated = self.api.authenticate(refresh_token=token, login_code=result)
  File "/usr/lib/python3.8/site-packages/minigalaxy/api.py", line 28, in authenticate
    return self.__get_token(login_code)
  File "/usr/lib/python3.8/site-packages/minigalaxy/api.py", line 63, in __get_token
    self.active_token = response_params['access_token']
KeyError: 'access_token'

**Comment by sharkwouter** [comment]
Try launching with ``MG_DEBUG=1 minigalaxy`` then you can see what the server responds. Do not post the full log with this enabled until after you've removed you passwords and tokens from it, though.

**Comment by lotth** [comment]
Same trace with MG_DEBUG=1. Could it be that Fedora did not compile minigalaxy with this option?

**Comment by sharkwouter** [comment]
Maybe I did not actually make auth priny what is it doing with MG_DEBUG. Could you try starting as ``minigalaxy --reset`` once. It might be an issue with the configuration file.

**Comment by lotth** [comment]
Same effect.

**Comment by sharkwouter** [comment]
Shame, I'll need to look into this some more to see if I can reproduce this then. I'll probably find some time for this tonight, otherwise later this week.

**Comment by sharkwouter** [comment]
Just to make sure, you don't have a firewall configuration which would block this, right?

**Comment by lotth** [comment]
No, I don't. Initial connection with the server seems to work as I receive requests for two-factor code, and associated email is sent correctly.
I also tried with and without VPN, with no success.

**Comment by sharkwouter** [comment]
Okay, thanks. It's probably an issue with Minigalaxy then.

**Comment by sharkwouter** [comment]
I have not been able to reproduce this on the current master branch. I don't think the code for logging in has changed, though.

Could you try cloning the repo and running it?

**Comment by lotth** [comment]
I tried cloning the master, same issue happens. It may be originating in my Fedora environment?

**Comment by sharkwouter** [comment]
Maybe, it could be the firewall.

**Comment by sharkwouter** [comment]
The last thing I can think of which might fix the problem is starting minigalaxy with the reset option from the command line: ``minigalaxy --reset``

Otherwise I have no idea. I have not been able to reproduce this issue so far.

**Comment by lotth** [comment]
Thank you for the advice. I tried but had the same problem.
I'll retry after the next Fedora update.

**Comment by sharkwouter** [comment]
Might be related to #257

**Comment by makson96** [comment]
@lotth could you check if this issue is fixed with current code from master branch?

**Comment by lotth** [comment]
Using the bin from master branch, the good news is that it does not crash.
But the first time I entered my email and password (those which work on gog.com website), I received the 4-digits code by email, entered them and got back to the login window. In all the next attempts, it gets back to the login window every time without any more 4-digits code request (for which I receive no more email).
I had no trace with MG_DEBUG=1 and no change after using --reset.

**Comment by sharkwouter** [comment]
We've implemented some fixes which may resolve this. @lotth would it be possible to test this once more?

**Comment by lotth** [comment]
Sure. I just downloaded the master branch, and got the same behavior : first time I tried, I I entered login and password then received an email with the 4-digit code. After code entry in minigalaxy, it got back to the login/password window. On next attempts, I did not receive the emails with the code and minigalaxy reverted to the login/password without presenting the code entry fields. Weird thing that all subsequent attempts lead to the same behavior, whether I quit minigalaxy or not.
No difference with --reset.

**Comment by sharkwouter** [comment]
I'm so confused by this, but thanks for testing again. I'm not sure what to do by this point.
