### ISSUE TITLE
DLC downloading fails

### ISSUE THREAD

**Issue by stephanlachnit** [sharkwouter/minigalaxy#254]
I probably didn't see it before because of #251, but for me downloading DLCs fails. Once clicking on the download button I get in the console:

```
$ bin/minigalaxy
Executing integrity check for /home/stephan/.cache/minigalaxy/download/Prison Architect/prison_architect_cleared_for_transfer_the_rock_3904_40671.sh
Verifying archive integrity... MD5 checksums are OK. All good.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/minigalaxy/minigalaxy/download.py", line 26, in finish
    self.__finish_func()
  File "/tmp/minigalaxy/minigalaxy/ui/gametile.py", line 342, in <lambda>
    finish_func = lambda: self.__install_dlc(dlc_title=dlc_title)
  File "/tmp/minigalaxy/minigalaxy/ui/gametile.py", line 349, in __install_dlc
    install_success = self.__install(dlc_title=dlc_title)
  File "/tmp/minigalaxy/minigalaxy/ui/gametile.py", line 295, in __install
    self.game.set_dlc_info("version", self.api.get_version(self.game, dlc_title=dlc_title), dlc_title)
TypeError: get_version() got an unexpected keyword argument 'dlc_title'
```

Seems like that should be `dlc_name`:
https://github.com/sharkwouter/minigalaxy/blob/d56be7a2d499976fa7ebe4311091e99c85124865/minigalaxy/api.py#L175

**Comment by makson96** [comment]
Uff, that's a shame that this bug which blocks important feature get pass 1.0.1 version mark.
