### ISSUE TITLE
AttributeError: 'Api' object has no attribute 'active_token_expiration_time'

### ISSUE THREAD

**Issue by etam** [sharkwouter/minigalaxy#262]
OS: openSUSE Tumbleweed
minigalaxy version: 1.0.1 installed from repo

On first launch:
```
Traceback (most recent call last):
  File "/usr/bin/minigalaxy", line 66, in <module>
    main()
  File "/usr/bin/minigalaxy", line 60, in main
    window = Window(APPLICATION_NAME)
  File "/usr/lib/python3.8/site-packages/minigalaxy/ui/window.py", line 54, in __init__
    self.HeaderBar.set_subtitle(self.api.get_user_info())
  File "/usr/lib/python3.8/site-packages/minigalaxy/api.py", line 170, in get_user_info
    response = self.__request(url)
  File "/usr/lib/python3.8/site-packages/minigalaxy/api.py", line 204, in __request
    if self.active_token_expiration_time < time.time():
AttributeError: 'Api' object has no attribute 'active_token_expiration_time'
```

**Comment by makson96** [comment]
Could you check if that fix it:
1. Run: sudo gedit /usr/lib/python3.8/site-packages/minigalaxy/api.py
2. add line 22:
```
self.active_token_expiration_time = time.time()
```
so it would look like
```
...
        self.debug = os.environ.get("MG_DEBUG")
        self.active_token = False
        self.active_token_expiration_time = time.time()

    # use a method to authenticate, based on the information we have
    # Returns an empty string if no information was entered
...
```
3. Start Minigalaxy again

**Comment by sharkwouter** [comment]
@makson96 is this related to #257?

**Comment by makson96** [comment]
It doesn't look so. This crash happens earlier so fix in this pull request won't probably fix that.

**Comment by sharkwouter** [comment]
That's a shame, looks pretty bad. I'll make a list with some of these kinds of issues which are small in terms of code, but need fixing. We need a new release quickly I'm afraid.

**Comment by sharkwouter** [comment]
I've added this issue to https://github.com/sharkwouter/minigalaxy/milestone/8

**Comment by etam** [comment]
@makson96 It works with your change

**Comment by sharkwouter** [comment]
Great, we should do a formal patch for this scenario then.
