### ISSUE TITLE
Metro Exodus DLCS not working

### ISSUE THREAD

**Issue by WolfMad** [sharkwouter/minigalaxy#276]
I have Metro Exodus plus the two DLCs Sam's Story and The Two Colonels when I try to start the game I get an error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/gametile.py", line 113, in on_button_click
    err_msg = start_game(self.game)
  File "/usr/lib/python3/dist-packages/minigalaxy/launcher.py", line 24, in start_game
    error_message, process = run_game_subprocess(game)
  File "/usr/lib/python3/dist-packages/minigalaxy/launcher.py", line 152, in run_game_subprocess
    process = subprocess.Popen(get_execute_command(game), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3/dist-packages/minigalaxy/launcher.py", line 37, in get_execute_command
    exe_cmd = get_windows_exe_cmd(game, files)
  File "/usr/lib/python3/dist-packages/minigalaxy/launcher.py", line 81, in get_windows_exe_cmd
    if "workingDir" in info["playTasks"][0] and info["playTasks"][0]["workingDir"]:
IndexError: list index out of range
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_games_minigalaxy.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/gametile.py", line 113, in on_button_click
    err_msg = start_game(self.game)
  File "/usr/lib/python3/dist-packages/minigalaxy/launcher.py", line 24, in start_game
    error_message, process = run_game_subprocess(game)
  File "/usr/lib/python3/dist-packages/minigalaxy/launcher.py", line 152, in run_game_subprocess
    process = subprocess.Popen(get_execute_command(game), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3/dist-packages/minigalaxy/launcher.py", line 37, in get_execute_command
    exe_cmd = get_windows_exe_cmd(game, files)
  File "/usr/lib/python3/dist-packages/minigalaxy/launcher.py", line 81, in get_windows_exe_cmd
    if "workingDir" in info["playTasks"][0] and info["playTasks"][0]["workingDir"]:
IndexError: list index out of range

if I open the folder /home/UserName/GOG Games/Metro Exodus and delete goggame-1414471894.info and goggame-2063590233.info then start the game DLC looks like it is not loaded if I go to the chapter select screen the DLC is locked but if I try to load a save file from the DLC I get the error "the saved game cannot be loaded Downloadable content "DLC Name" is missing"

I have tried copying the game files from a working Windows install and that did not work

**Comment by makson96** [comment]
Thanks for the report.
Important note here is that this is Windows only game on GoG.
I will see what we can do with this.
