### ISSUE TITLE
Handle broken downloads / not enough space on file system error

### ISSUE THREAD

**Issue by tastytea** [sharkwouter/minigalaxy#286]
Version: 1.0.2

The download of a game stopped with no feedback. I restarted minigalaxy from a terminal. It said `Resuming download […]` and then tried to run the partially downloaded installer, which of course failed. I manually deleted the cache and ran restarted minigalaxy again. There I saw this error:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/minigalaxy/download_manager.py", line 72, in __download_thread
    self.__download_file(self.__current_download)
  File "/usr/lib/python3.8/site-packages/minigalaxy/download_manager.py", line 83, in __download_file
    result = self.download_operation(download, start_point, download_mode)
  File "/usr/lib/python3.8/site-packages/minigalaxy/download_manager.py", line 139, in download_operation
    save_file.write(chunk)
OSError: [Errno 28] Auf dem Gerät ist kein Speicherplatz mehr verfügbar
```

“Auf dem Gerät ist kein Speicherplatz mehr verfügbar” means “There is no space available on the device anymore”.

* Please catch the error and report it in the GUI. (Maybe catch all exceptions and display the raw output of unknown ones, to at least signal that something went wrong?)
* Please check if the installer is corrupted. (If you don't have access to checksums, a file size check would be better than nothing!)

**Comment by sharkwouter** [comment]
Thanks for the report. This is related to https://github.com/sharkwouter/minigalaxy/pull/147

**Comment by sharkwouter** [comment]
A disk space check has now been implemented on the master branch. Thanks for the report!
