### ISSUE TITLE
Updating Metal Slug failed

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#351]
This is about a Windows game which was being extracted using Innoextract. I got this error while trying to update:

```
Resuming download /home/wouter/.cache/minigalaxy/download/METAL SLUG/setup_metal_slug_gog-3_(12273).exe
Exception in thread Thread-604:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wouter/Personal/minigalaxy/minigalaxy/download.py", line 26, in finish
    self.__finish_func()
  File "/home/wouter/Personal/minigalaxy/minigalaxy/ui/gametile.py", line 338, in __update
    install_success = self.__install(update=True)
  File "/home/wouter/Personal/minigalaxy/minigalaxy/ui/gametile.py", line 299, in __install
    err_msg = install_game(self.game, installer)
  File "/home/wouter/Personal/minigalaxy/minigalaxy/installer.py", line 45, in install_game
    error_message = verify_installer_integrity(game, installer)
  File "/home/wouter/Personal/minigalaxy/minigalaxy/installer.py", line 72, in verify_installer_integrity
    with open(os.path.join(os.path.dirname(installer), installer_file_name), "rb") as installer_file:
IsADirectoryError: [Errno 21] Is a directory: '/home/wouter/.cache/minigalaxy/download/METAL SLUG/app'
```

This is the content of the ``METAL SLUG`` directory:

```
wouter@wouter-XPS-15-9500:~$ ls -l /home/wouter/.cache/minigalaxy/download/METAL\ SLUG/
total 58660
drwxrwxr-x 4 wouter wouter     4096 Apr 13 15:38  app
drwxr-xr-x 3 wouter wouter     4096 Apr 13 16:11 'setup_metal_slug_gog-3_(12273)'
-rw-rw-r-- 1 wouter wouter 60049272 Apr 13 15:22 'setup_metal_slug_gog-3_(12273).exe'
-rw-rw-r-- 1 wouter wouter      136 Apr 13 16:20  test.txt
drwxrwxr-x 3 wouter wouter     4096 Apr 13 15:37  tmp
```

**Comment by sharkwouter** [comment]
I've removed the files and it seems to work fine now. Not sure what happened. These files were really old.
