### ISSUE TITLE
When env variable LANG is set, translations don't load

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#408]
Crystal reported on Discord that is LANG is set to C, the Minigalaxy crashes with the following error:

```
Traceback (most recent call last):
  File "/usr/bin/minigalaxy", line 64, in <module>
    main()
  File "/usr/bin/minigalaxy", line 54, in main
    from minigalaxy.ui.gtk import Gtk
  File "/usr/lib/python3.9/site-packages/minigalaxy/ui/__init__.py", line 3, in <module>
    from minigalaxy.ui.window import Window             # noqa: F401
  File "/usr/lib/python3.9/site-packages/minigalaxy/ui/window.py", line 4, in <module>
    from minigalaxy.ui.login import Login
  File "/usr/lib/python3.9/site-packages/minigalaxy/ui/login.py", line 3, in <module>
    from minigalaxy.translation import _
  File "/usr/lib/python3.9/site-packages/minigalaxy/translation.py", line 32, in <module>
    lang = gettext.translation(TRANSLATION_DOMAIN, LOCALE_DIR, languages=[default_locale], fallback=True)
  File "/usr/lib/python3.9/gettext.py", line 587, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/usr/lib/python3.9/gettext.py", line 558, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib/python3.9/gettext.py", line 213, in _expand_lang
    loc = locale.normalize(loc)
  File "/usr/lib/python3.9/locale.py", line 403, in normalize
    code = localename.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

I suggest unsetting the LANG and making sure default locale cannot be C.

**Comment by GB609** [comment]
I tried - and used - the following commands to run MG from the git source dir:

```sh
LANG=C python -m minigalaxy
LC_ALL=C python -m minigalaxy
```

Both start up with no issue at all. This seems fixed. Of course, it'll start up in the default, none-translated variant (which it should), so all seems fine.

**Comment by sharkwouter** [comment]
Thanks for testing
