### ISSUE TITLE
Fedora 34 - import error with urllib3

### ISSUE THREAD

**Issue by montaropdf** [sharkwouter/minigalaxy#446]
Hello,

I just install minigalaxy using dnf, unfortunatelly, the program can't load due to the following error:

```
Traceback (most recent call last):
  File "/usr/bin/minigalaxy", line 64, in <module>
    main()
  File "/usr/bin/minigalaxy", line 54, in main
    from minigalaxy.ui.gtk import Gtk
  File "/usr/lib/python3.9/site-packages/minigalaxy/ui/__init__.py", line 3, in <module>
    from minigalaxy.ui.window import Window             # noqa: F401
  File "/usr/lib/python3.9/site-packages/minigalaxy/ui/window.py", line 5, in <module>
    from minigalaxy.ui.preferences import Preferences
  File "/usr/lib/python3.9/site-packages/minigalaxy/ui/preferences.py", line 6, in <module>
    from minigalaxy.constants import SUPPORTED_DOWNLOAD_LANGUAGES, SUPPORTED_LOCALES
  File "/usr/lib/python3.9/site-packages/minigalaxy/constants.py", line 1, in <module>
    import requests
  File "/usr/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
```

If I start the python repl, I can import `urllib3` and `requests` without error, so I suspect a version conflict or a bad python environment definition by the application.

Below are the information, from pip, about the 2 offending libraries.
``` bash
bash-5.1$ pip show requests
Name: requests
Version: 2.27.1
Summary: Python HTTP for Humans.
Home-page: https://requests.readthedocs.io
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /home/roland/.local/lib/python3.9/site-packages
Requires: certifi, charset-normalizer, idna, urllib3
Required-by: Kivy-Garden, koji, minigalaxy, proton-client, protonvpn-gui, pykickstart, requests-file, requests-ftp, requests-gssapi, requests_download
```
``` bash
bash-5.1$ pip show urllib3
Name: urllib3
Version: 1.26.8
Summary: HTTP library with thread-safe connection pooling, file post, and more.
Home-page: https://urllib3.readthedocs.io/
Author: Andrey Petrov
Author-email: andrey.petrov@shazow.net
License: MIT
Location: /home/roland/.local/lib/python3.9/site-packages
Requires: 
Required-by: requests
```

**Comment by sharkwouter** [comment]
You might want to install the requests library using the package manager instead of pip. It seems there is some kind of version mismatch on your system. I wouldn't know what else it going on, but it seems like it's either a Fedora issue or something on your system.

**Comment by montaropdf** [comment]
It appears that the problem was linked to the envvar `PYTHONPATH`, that was not defined.

Even if it seems obvious, mentioning that this variable needs to be set appropriately, could help with diagnosing common issues.

**Comment by sharkwouter** [comment]
I'm going to close this for now, as it does not seem to be a problem with Minigalaxy itself.
