### ISSUE TITLE
Test test1_set_info failed

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#496]
```
Run python -m unittest tests/*.py
  python -m unittest tests/*.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.1[2](https://github.com/sharkwouter/minigalaxy/runs/6722058661?check_suite_focus=true#step:7:2)/x64
........................................F..............................................................................
Couldn't read xml data. Response with code 200 received with the following content: 
Couldn't find md5 in xml checksum data
Couldn't find md5 in xml checksum data
Couldn't read xml data. Response with code 404 received with the following content: <MagicMock name='mock().text' id='14045048[3](https://github.com/sharkwouter/minigalaxy/runs/6722058661?check_suite_focus=true#step:7:3)023936'>
Couldn't find md5 in xml checksum data
Couldn't read xml data. Response with code 200 received with the following content: 
Couldn't find file size in xml checksum data
Couldn't find file size in xml checksum data
Couldn't read xml data. Response with code [4](https://github.com/sharkwouter/minigalaxy/runs/6722058661?check_suite_focus=true#step:7:4)04 received with the following content: <MagicMock name='mock().text' id='1404[5](https://github.com/sharkwouter/minigalaxy/runs/6722058661?check_suite_focus=true#step:7:5)0482883840'>
Couldn't find file size in xml checksum data
beneath_a_steel_sky_en_gog_2_20150.sh integrity is preserved. MD5 is: 5cc[6](https://github.com/sharkwouter/minigalaxy/runs/6722058661?check_suite_focus=true#step:7:7)824[7](https://github.com/sharkwouter/minigalaxy/runs/6722058661?check_suite_focus=true#step:7:8)b61ba31e37e[8](https://github.com/sharkwouter/minigalaxy/runs/6722058661?check_suite_focus=true#step:7:9)42fd0440[9](https://github.com/sharkwouter/minigalaxy/runs/6722058661?check_suite_focus=true#step:7:10)d98
Using system's scrummvm to launch Beneath A Steel Sky
Using system's dosbox to launch Test Game
Using system's scrummvm to launch Test Game
mock: line 1 column 1 (char 0)
======================================================================
FAIL: test1_set_info (tests.test_game.TestGame)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/home/runner/work/minigalaxy/minigalaxy/tests/test_game.py", line 151, in test1_set_info
    self.assertEqual(expected, observed)
AssertionError: '{"version": "gog-3"}' != '{"locale": "", "view": "grid", "install_dir[270 chars]-3"}'
- {"version": "gog-3"}
+ {"locale": "", "view": "grid", "install_dir": "/home/runner/GOG Games", "keep_installers": false, "stay_logged_in": true, "use_dark_theme": false, "show_hidden_games": false, "show_windows_games": false, "keep_window_maximized": false, "installed_filter": false, "create_applications_file": false}{"version": "gog-3"}


----------------------------------------------------------------------
Ran [11](https://github.com/sharkwouter/minigalaxy/runs/6722058661?check_suite_focus=true#step:7:12)9 tests in 0.[25](https://github.com/sharkwouter/minigalaxy/runs/6722058661?check_suite_focus=true#step:7:26)0s

FAILED (failures=1)
Error: Process completed with exit code 1.
```
It fails since this commit: https://github.com/sharkwouter/minigalaxy/commit/8bea90718b72486e366a0750e145bc9cca3c9410

Seems like a mistake in the test itself, but I'm not sure. Maybe @makson96 knows.

**Comment by sharkwouter** [comment]
I'm removing the release critical tag, because this has not happened again. This test seems to be a bit flaky, but I'm not sure why.

**Comment by sharkwouter** [comment]
I haven't seen this fail in a while, so I'm closing it.
