### ISSUE TITLE
"Rise of the Triad: Dark War" doesn't download

### ISSUE THREAD

**Issue by LukasThyWalls** [sharkwouter/minigalaxy#502]
Hello!

About this game: Rise of the Triad: Dark War https://www.gog.com/game/rise_of_the_triad__dark_war

When you try to download via minigalaxy, it stops in "En Cola" (queued in Spanish) and it does nothing more.

Executing minigalaxy via terminal, when i try to download the game it throws this:

```
Exception in thread Thread-290 (__download_game):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/gametile.py", line 218, in __download_game
    result = self.__download(download_info, finish_func, cancel_to_state)
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/gametile.py", line 239, in __download
    total_file_size += int(self.api.get_file_size(file_info["downlink"]))
  File "/usr/lib/python3/dist-packages/minigalaxy/api.py", line 177, in get_file_size
    root = ET.fromstring(xml_string)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1350, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

```

Thanks!

**Comment by sharkwouter** [comment]
Thanks for the report @LukasThyWalls! This is probably related to #484. I've just made an update to the master branch. Could download that and try again?
