### ISSUE TITLE
Stellaris: Utopia will not install

### ISSUE THREAD

**Issue by NonMeme** [sharkwouter/minigalaxy#511]
I own Stellaris through GOG. I can install all the DLC except for Utopia. Here's the message that comes up in Terminal.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 401, in _decode
    data = self._decoder.decompress(data)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 88, in decompress
    ret += self._obj.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 548, in read
    data = self._decode(data, decode_content, flush_decoder)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 404, in _decode
    raise DecodeError(
urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/gametile.py", line 384, in <lambda>
    self.dlc_dict[title][0].connect("clicked", lambda x: self.__download_dlc(installer))
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/gametile.py", line 349, in __download_dlc
    result = self.__download(download_info, finish_func, cancel_to_state)
  File "/usr/lib/python3/dist-packages/minigalaxy/ui/gametile.py", line 239, in __download
    total_file_size += int(self.api.get_file_size(file_info["downlink"]))
  File "/usr/lib/python3/dist-packages/minigalaxy/api.py", line 176, in get_file_size
    xml_string = SESSION.get(xml_link).text
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 697, in send
    r.content
  File "/usr/lib/python3/dist-packages/requests/models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3/dist-packages/requests/models.py", line 758, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))

**Comment by sharkwouter** [comment]
Thanks for the report. I wonder if this happens with more downloads. It could be an issue on  GOGs side, could be an issue on our side. I don't own this game, though, so I'm not sure how to debug it.
