### ISSUE TITLE
Fixing Minigalaxy "download_manager.py" file in openSUSE Leap 15.4 (Python 3.6)

### ISSUE THREAD

**Issue by josue2363** [sharkwouter/minigalaxy#528]
Forgive me if I'm doing this in the wrong place, but I had to share this. Is there any chance that someone using openSUSE Leap 15.4 is experiencing the same issue:
- Game images are not displayed correctly.
- The download of games does not start correctly, leaving only the status "queued".

It looks like this happens in openSUSE Leap 15.4 because of Python 3.6. I'm not very knowledgeable with Python language, but doing a search, I got the following solution: change the download_manager.py file (in Leap 15.4, located in the directory: _/usr/lib/python3.6/site-packages/minigalaxy/_) in the following way:

Change the line: self.queue_time = time._time_ns_()
To the following: self.queue_time = time.**time**()

For users, a quick command:
`sudo sed -i 's/time_ns/time/' /usr/lib/python3.6/site-packages/minigalaxy/download_manager.py`

After these small changes, the game images load normally again and I can finally download the games.

Before making this change, when running Minigalaxy from the Terminal, I received the following output:

```
josue@josue-pc:~> minigalaxy
Traceback (most recent call last):
  File "/usr/bin/minigalaxy", line 16, in <module>
    from minigalaxy.version import VERSION
ModuleNotFoundError: No module named 'minigalaxy'
josue@josue-pc:~> minigalaxy
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/minigalaxy/ui/gametile.py", line 182, in load_thumbnail
    DownloadManager.download_now(download)
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 143, in download_now
    self.__ui_queue.put(QueuedDownloadItem(download, 0))
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 44, in __init__
    self.queue_time = time.time_ns()
AttributeError: module 'time' has no attribute 'time_ns'

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/minigalaxy/ui/gametile.py", line 182, in load_thumbnail
    DownloadManager.download_now(download)
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 143, in download_now
    self.__ui_queue.put(QueuedDownloadItem(download, 0))
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 44, in __init__
    self.queue_time = time.time_ns()
AttributeError: module 'time' has no attribute 'time_ns'

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/minigalaxy/ui/gametile.py", line 182, in load_thumbnail
    DownloadManager.download_now(download)
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 143, in download_now
    self.__ui_queue.put(QueuedDownloadItem(download, 0))
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 44, in __init__
    self.queue_time = time.time_ns()
AttributeError: module 'time' has no attribute 'time_ns'

Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/minigalaxy/ui/gametile.py", line 182, in load_thumbnail
    DownloadManager.download_now(download)
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 143, in download_now
    self.__ui_queue.put(QueuedDownloadItem(download, 0))
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 44, in __init__
    self.queue_time = time.time_ns()
AttributeError: module 'time' has no attribute 'time_ns'

Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/minigalaxy/ui/gametile.py", line 182, in load_thumbnail
    DownloadManager.download_now(download)
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 143, in download_now
    self.__ui_queue.put(QueuedDownloadItem(download, 0))
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 44, in __init__
    self.queue_time = time.time_ns()
AttributeError: module 'time' has no attribute 'time_ns'

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/minigalaxy/ui/gametile.py", line 182, in load_thumbnail
    DownloadManager.download_now(download)
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 143, in download_now
    self.__ui_queue.put(QueuedDownloadItem(download, 0))
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 44, in __init__
    self.queue_time = time.time_ns()
AttributeError: module 'time' has no attribute 'time_ns'

Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/minigalaxy/ui/gametile.py", line 182, in load_thumbnail
    DownloadManager.download_now(download)
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 143, in download_now
    self.__ui_queue.put(QueuedDownloadItem(download, 0))
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 44, in __init__
    self.queue_time = time.time_ns()
AttributeError: module 'time' has no attribute 'time_ns'

Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/minigalaxy/ui/gametile.py", line 182, in load_thumbnail
    DownloadManager.download_now(download)
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 143, in download_now
    self.__ui_queue.put(QueuedDownloadItem(download, 0))
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 44, in __init__
    self.queue_time = time.time_ns()
AttributeError: module 'time' has no attribute 'time_ns'

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/minigalaxy/ui/gametile.py", line 182, in load_thumbnail
    DownloadManager.download_now(download)
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 143, in download_now
    self.__ui_queue.put(QueuedDownloadItem(download, 0))
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 44, in __init__
    self.queue_time = time.time_ns()
AttributeError: module 'time' has no attribute 'time_ns'

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/minigalaxy/ui/gametile.py", line 182, in load_thumbnail
    DownloadManager.download_now(download)
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 143, in download_now
    self.__ui_queue.put(QueuedDownloadItem(download, 0))
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 44, in __init__
    self.queue_time = time.time_ns()
AttributeError: module 'time' has no attribute 'time_ns'

Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/minigalaxy/ui/gametile.py", line 182, in load_thumbnail
    DownloadManager.download_now(download)
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 143, in download_now
    self.__ui_queue.put(QueuedDownloadItem(download, 0))
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 44, in __init__
    self.queue_time = time.time_ns()
AttributeError: module 'time' has no attribute 'time_ns'

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/minigalaxy/ui/gametile.py", line 182, in load_thumbnail
    DownloadManager.download_now(download)
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 143, in download_now
    self.__ui_queue.put(QueuedDownloadItem(download, 0))
  File "/usr/lib/python3.6/site-packages/minigalaxy/download_manager.py", line 44, in __init__
    self.queue_time = time.time_ns()
AttributeError: module 'time' has no attribute 'time_ns'
```
To the developers, thank you very much for making Minigalaxy. ❤

**Comment by sharkwouter** [comment]
Thanks for this report, this is the kind of thing you'd forget. I'll put it on the list. I'm doing some major changes to make the code more maintainable at the moment. I'm sure I can fit this in.

**Comment by cmagnificent** [comment]
This issue appears to be currently affecting the flathub release as well. Same behavior, Minigalaxy attempts to resume a previous download and there is excessive cpu usage.

**Comment by sharkwouter** [comment]
I've fix this in master now. The fix will be in the next release.
