### ISSUE TITLE
error when downloading the long journey home

### ISSUE THREAD

**Issue by alexmo1997** [sharkwouter/minigalaxy#552]
when downloading tljh, i get the following error after the progress bar is at about half:
```
Exception in thread Thread-6 (<lambda>):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/python3.10/site-packages/minigalaxy/download_manager.py", line 96, in <lambda>
    download_thread = threading.Thread(target=lambda: self.__download_thread(q))
  File "/app/lib/python3.10/site-packages/minigalaxy/download_manager.py", line 268, in __download_thread
    self.__download_file(download, download_queue)
  File "/app/lib/python3.10/site-packages/minigalaxy/download_manager.py", line 283, in __download_file
    self.__prepare_location(download.save_location)
  File "/app/lib/python3.10/site-packages/minigalaxy/download_manager.py", line 322, in __prepare_location
    os.makedirs(save_directory, mode=0o755)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/alex/.var/app/io.github.sharkwouter.Minigalaxy/cache/minigalaxy/download/The Long Journey Home'
```

**Comment by sharkwouter** [comment]
Thanks for the report. This is something that should not happen for sure. I put it on the list of issues that should be fixed for the next release.

**Comment by GB609** [comment]
@alexmo1997 Any chance you could re-test this? I think the download handling should be much better since quite a few releases already.
