### ISSUE TITLE
Launching Unreal Gold leads to minigalaxy error with backtrace

### ISSUE THREAD

**Issue by ell1e** [sharkwouter/minigalaxy#619]
Trying to launch Unreal Gold leads to minigalaxy error with backtrace:
```
~ $ flatpak run io.github.sharkwouter.Minigalaxy
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/minigalaxy/ui/gametile.py", line 121, in on_button_click
    err_msg = start_game(self.game)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/minigalaxy/launcher.py", line 48, in start_game
    error_message, process = run_game_subprocess(game)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/minigalaxy/launcher.py", line 205, in run_game_subprocess
    get_execute_command(game),
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/minigalaxy/launcher.py", line 65, in get_execute_command
    exe_cmd = get_windows_exe_cmd(game, files)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/minigalaxy/launcher.py", line 142, in get_windows_exe_cmd
    filename = os.path.splitext(os.path.basename(executables[0]))[0] + '.exe'
                                                 ~~~~~~~~~~~^^^
IndexError: list index out of range
```
It seems like the install has worked fine though, so I think the wine prefix setup and everything works and only launching it once it's ready to go doesn't work.

**Affected minigalaxy version:** 1.3.0 (from flathub)

**Comment by sharkwouter** [comment]
Interesting, my guess is that there is no binary in the root directory of Unreal Gold. It is probably in a bin directory. I do have this game, maybe I can figure this one out.

**Comment by sharkwouter** [comment]
Turns out I was right, Unreal Gold has no exe files in the main directory and no config file which shows where to find the executable.

**Comment by ell1e** [comment]
minigalaxy 1.3.2 seems to try to launch some random foxit reader install inside the Unreal Gold folder now. 😆 It doesn't seem to guess the game executable correctly.

**Comment by GB609** [comment]
Have you tried a full delete + uninstall?

Could you provide an ls of the game dir?
And also the content of the file goggame*.info?

**Comment by sharkwouter** [comment]
Yeah, Unreal Gold is hard to deal with. There is no info file, so Minigalaxy has to guess. You can delete the exe files which you don't need. I would like to offer the user a selection menu in these cases, but I haven't gotten to that yet.

**Comment by GB609** [comment]
> Yeah, Unreal Gold is hard to deal with. There is no info file, so Minigalaxy has to guess. You can delete the exe files which you don't need. I would like to offer the user a selection menu in these cases, but I haven't gotten to that yet.

Is there really no info file even after we changed the installation procedure? I was partly under the impression that the generation of these files might also depend a bit on proper installation and that the tests before often used innoextract unpacking.

**Comment by sharkwouter** [comment]
No, there is no info file. There is a .ink file in the main directory, maybe we could launch that.

**Comment by GB609** [comment]
That would be another possibility to consider.

**Comment by sharkwouter** [comment]
I did a quick test with this code and wine can launch lnk files, which makes Unreal Gold start: https://github.com/sharkwouter/minigalaxy/commit/9f394dc449acae03287bb6213e4e4fcff13df518

**Comment by GB609** [comment]
That is good news.
But maybe we should consider, just like with the exe files, that there might be multiple link files. And that iteration order does not guarantee to get the right one.

**Comment by sharkwouter** [comment]
Yeah, agreed. This was just a test.

**Comment by ell1e** [comment]
There are a few more games I've found that cannot be launched because it picks the wrong executable:

- [Civ 3](https://www.gog.com/en/game/sid_meiers_civilization_iii_complete): it launches the level editor instead, which complains with some error that some file is missing and quits.

- [Lands of Lore 3](https://www.gog.com/en/game/lands_of_lore_3): it launches some nglide wrapper config tool instead, that happens to be included, from where the game cannot be launched.

- [Indiana Jones and the Internal Machine](https://www.gog.com/en/game/indiana_jones_and_the_infernal_machine): it launches some installer, that gets confused seemingly because the game is already installed.

Perhaps like for [DXVK](https://github.com/flathub/io.github.sharkwouter.Minigalaxy/issues/74) and missing dlls and such, it might be best to let people pull request some simple JSON file for games to override the executable path and subfolder, and to override additional winetricks install commands or something? I feel like that would be the most practical approach to address those issues.

**Comment by GB609** [comment]
I don't think keeping even more additional files for launch configurations is the right approach.
GOG or any game's devs could change a game's directory structure or launch arguments with every version if they wanted to. We'd never manage to keep up with this.

Plus, depending on where and how we fetch and integrate these launch commands, we're introducing a security issue as these jsons could contain any arbitrary command.

I'd rather add a dropdown in the Game properties that lists the possible variants we have:
1. playTasks from goggame*.info file
2. (if not 1) - found link files (because fewer and can also contain correct launch arguments)
3. (if not 2) - listing of executables (which requires a filter or we will add a lot of windows system executables as well)

We could then also open the property dialog on first launch when there is than one choice.

**Comment by ell1e** [comment]
It wouldn't have more security implications than any other pull request if it was a JSON file baked into minigalaxy. That would make updates take longer, but imho that would still be better than not addressing this.

Picking an executable list as well as not installing wine in a usable way for probably 30% of the average person's games (since e.g. the wide-spread need for DXVK is currently unaddressed) has the problem that non-technical users will check out at that point.

**Comment by sharkwouter** [comment]
I think we can solve a lot of problems if we prioritize link files over executables and maybe do some pattern matching to exclude files with config in the name and such. Then we'll have probably solved almost all cases. I'll look into it.

**Comment by ell1e** [comment]
I don't think game fixes taking an unspecified time until the next minigalaxy release is a big problem. I doubt the amount of huge game changes invalidating past fixes that you envision to happen will happen.

Nevertheless, I can't see the future ofc and I realize that's easy to say not being currently one of the people who would need to look over the process.

**Comment by GB609** [comment]
> Edit: regarding different wine versions, I think it would make sense to simply focus on flatpak. That would likely work with most other distributions, and where it doesn't, the user could always use the flatpak instead.

That wouldn't really solve the issue. When the flatpak upgrades the wine version, all configurations which minigalaxy already **has** would have to be re-tested and (if necessary) updated before the release with the upgrade. That also applies to new versions of stuff like DXVK. That requires constant, repeated contributions from people that actually own the games.

**Comment by ell1e** [comment]
Sure, you're correct. I might be severely underestimating this anyway, so feel free to not be convinced. I feel bad for discussing this for so long, it's your choice in any case.

But that said, I just think things aren't going to break *that* often for most older games, from my own wine experience in the past. And you only need a few users to cover the common ones to give everybody a pretty good experience compared to now. For example, I have 73 games installed via minigalaxy right now of which most use wine, and I'd happily pull request the obvious things like need for DXVK. If a lot of special quirks are needed, often it's better to wait for wine to improve compatibility out of the box anyway, but I imagine that won't affect most games on GOG. In any case, my apologies for harping on about this.

**Comment by GB609** [comment]
Well. I can't decide anything. At the end its a matter of:
 * Priority and
 * whether @sharkwouter would accept any PR for such a feature (or go at it himself)

Right now, there's very few people working on Minigalaxy. And i think we should first improve on those areas for which the users can't reasonably apply workarounds themselves before we introduce something new that adds to the overall upkeeping workload instead. The stuff that actually keeps the users from even getting to the point of game configuration.
That is my personal priority right now. After that, i will look at improvements to launching or configuring wine games again (or using alternative runners like umu) because that was the initial reason i started contributing to MG. I want to integrate MG in my couch gaming PC, preferably without any need for a keyboard. So my goal aligns with yours at the end. I want to install and run games without any subsequent need for hacks or configurations. I just think that there is a more effective way to get there by not spending effort on our own little list, but join in on umu-db instead.
My point being: The lists you want are already there, just not within minigalaxy itself. And the joint list would be easier to maintain for all. This is not that different from the result you want at the end. Just another way to get there where we wouldn't even have to start from scratch.

I certainly agree, wine research and configuration can be tedious. It takes effort. But the users can do something there themselves for now. They can't do anything when the downloads don't work.

**Comment by sharkwouter** [comment]
I created a PR for this issue: https://github.com/sharkwouter/minigalaxy/pull/666

**Comment by ell1e** [comment]
Based on the latest flatpak version of minigalaxy, here are a few more common wrong executables:

*Lands of Lore 3:* seems to be launching either `app/ngilde_config.exe` or `Lands of Lore 3/nglide_config.exe`, should be launching `Lands of Lore 3/LOL3.exe`

*Lands of Lore 2 Guardians of Destiny:* seems to be launching `./tmp/setup_foxit.exe` (really? lol), should be launching `./app/DOSBOX/dosbox.exe`

*Quake II Original:* Seems to be launching `Q2Launcher.exe` which seems to be correct but it seems to lack mandatory command line arguments that are likely specified in the `.lnk`

*Unreal Gold:* Currently launches something foxit related, perhaps `./tmp/FoxitReader.exe`, should be launching `Unreal Gold/System/Unreal.exe` instead.

It would help with investigating this if the error message showing the wine errors actually also showed the path that was launched. It seems sometimes to be  impossible to find out via trial and error what it has been trying to launch.

**Comment by GB609** [comment]
> It would help with investigating this if the error message showing the wine errors actually also showed the path that was launched. It seems sometimes to be impossible to find out via trial and error what it has been trying to launch.

Running Minigalaxy in debug mode will print this.
`flatpak --env=MG_DEBUG=1 ...`

Format of the log line: `Launch command for <game_name>: <command string>`.
If you are going to report more issues like this, please make it a habit to also attach the respective game's `goggame*.info` file (if existing) and a simple `ls` of the game directory. This is valuable information. All games have a different structure which we simply don't know about if we don't own the games ourselves. And i certainly don't plan to buy **all** games that report errors just to get a look at its directory structure and metadata.

**Comment by ell1e** [comment]
I added the requested info by editing above comment. For what it's worth, I'm interested in gifting games if in a particular situation that might help with debugging a pesky corner case.

**Comment by GB609** [comment]
Thank you. There's a few more hints in the stuff you provided now.

**Comment by sharkwouter** [comment]
Yeah, the fix from the PR is not in 1.3.2. It will be in the next release. We should think about if we're at a point yet to do another release. I feel we could use some more stability fixes. There are some issues with the gui getting stuck while installing/downloading/running games on which I cannot put my finger. Maybe we are just using too many threads at the same time.

**Comment by ell1e** [comment]
Your work on the downloading stuff sounds downright amazing. This sounds really great.

**Comment by GB609** [comment]
A lot has been done already. There's a new dedicated UI to stop, pause and restart downloads. It also shows a size estimate and
even allows to change the number of parallel downloads. Plus some bug fixes.
What's missing is the overall progress bar percentage fix on the game tiles (plus the improved controls there) and a few more nice-to-haves which aren't really necessary for the basic functionality.
Feel free to have a look at the changelog.md on the master branch for more details of what's coming.

**Comment by GB609** [comment]
@ell1e 
I've had a look in your detailed post above again.
The entire directory structure of `Lands of Lore 2` and `Lands of Lore 3` appear strange.
They both contain a game directory named after the game and a directory `app`. Moreover, both directories seem to contain the same files (which the game named one also having goggame.info or lnk files)

It appears like some kind of mixed install between innoextract and wine.

Did you maybe install these games with an older version of minigalaxy first, then started an update installation over that afterwards?
If you don't have any save games, would you please try to fully uninstall and reinstall them? I'd like to see if the directory structure will be correct afterwards.
If yes, then the update installation might have some issue with correctly setting up the game directory name when the game directory exists already (because it is nested in itself).

If the game directories would just be what is in the sub directory named after the game, they should launch normally.

**Comment by ell1e** [comment]
Can confirm Lands of Lore 2 was wrongly installed and reinstall fixed it, it still doesn't launch [but it looks more like this is the problem now](https://github.com/flathub/io.github.sharkwouter.Minigalaxy/issues/86). For Lands of Lore 3, it however continues to launch the nglide configurator. Interestingly, in the new Lands of Lore 3 install, the goggame file is now gone.

**Comment by GB609** [comment]
Did you update the directory listings in the post above? In that case LoL3 should launch in the next release through the `.lnk` file even when there is no goggame.info.

**Comment by ell1e** [comment]
The `.lnk` seems to point to `LOL3.EXE`, it's the updated listing. But for some reason that doesn't seem to be picked up and it's launching the nglide config tool anyway.

**Comment by GB609** [comment]
It's not being picked up because the fix that uses .lnk is not yet in release 1.3.2
