### ISSUE TITLE
Fedora 31, error `zipfile.BadZipFile: File is not a zip file`

### ISSUE THREAD

**Issue by pcfe** [sharkwouter/minigalaxy#92]
Hello,

with `minigalaxy-0.9.2-1.fc31.noarch` I get 

```
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/site-packages/minigalaxy/window/gametile.py", line 132, in __download_file
    self.__install_game()
  File "/usr/lib/python3.7/site-packages/minigalaxy/window/gametile.py", line 151, in __install_game
    with zipfile.ZipFile(installer_path) as archive:
  File "/usr/lib64/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/usr/lib64/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

when I try to install any game.

If I look in `/.cache/minigalaxy/download/`, I find 3 files name ending in `.sh` that are actually html files of a server complaining _We have temporarily blocked your access to our website…_

Please add handling of the fact that the server may not return a shell script.

`cat Akalabeth\:\ World\ of\ Doom.sh`

```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>GOG.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

        <!-- TODO: add favicons -->

    	<style type="text/css">
			html,
			body { height:100%; }
			body { margin:0; padding:0; 
				background-color:#ccc;
				background-image:-moz-linear-gradient(top, #bdbdbd, #ccc);
				background-image:-o-linear-gradient(top, #bdbdbd, #ccc);
				background-image:-webkit-linear-gradient(top, #BDBDBD, #ccc);
				background-image:linear-gradient(to bottom, #BDBDBD, #ccc);
				background-size:100% 486px; background-position:50% 0; background-repeat:repeat-x;
				color:#262626;
				font-family: 'Open Sans', sans-serif; 
			}
				.wrapper { display:table; 
					max-width:50em; height:100%; padding:0 5%; margin:0 auto;
				}
					.content { display:table-cell; 
						vertical-align:middle; 
					}
						p { margin-top:1em; font-size:1.2em; line-height:1.5; text-align:justify; }
						h1 { font-weight:300; font-size:2em; }
    	</style>
    </head>
    <body>
		<div class="wrapper">
			<div class="content">
				<p>
					We have temporarily blocked your access to our website because You have exceeded number of simultaneous connections. Sorry for any inconvenience this may cause.
				</p>
				<p>
					If you see this message very often, please contact our Support Team immediately after you are able to access GOG.com normally.
				</p>
			</div>
		</div>
    </body>
</html>

```

should I look closer at one of these files?

```
pcfe@t7910 minigalaxy $ tree
.
├── download
│   ├── Akalabeth: World of Doom.sh
│   ├── Beneath a Steel Sky.sh
│   └── Overload - Playable Teaser.sh
├── extract
│   ├── 1207658695
│   ├── 1207666073
│   └── 1245077743
├── thumbnails
│   ├── 1129701343.jpg
│   ├── 1207658694.jpg
│   ├── 1207658695.jpg
│   ├── 1207659142.jpg
│   ├── 1207659221.jpg
│   ├── 1207659693.jpg
│   ├── 1207666073.jpg
│   ├── 1245077743.jpg
│   ├── 1449569170.jpg
│   ├── 1748855533.jpg
│   ├── 2016844216.jpg
│   └── 2020648154.jpg
└── WebKitCache
    └── Version 14
        ├── Blobs
        │   ├── 01FD4E285D0B6802D137D45ED11C951B68CE1FD8
        │   ├── 6E7CD8B5BEF84B6100DAA3D5152726D640738BB6
        │   ├── D89AAB7C009CC2215D463726649DD32A167C28AF
        │   ├── DA9A3A8E7A1A81D8CDF0F3233967BD992E9DD499
        │   └── F8325BC7B20A1195CB092999FB0E0A94C8A9262B
        ├── Records
        │   └── 30DC4B5F0E11084A963B8ED5D0152982B6298948
        │       ├── Resource
        │       │   ├── 04D071FB65534B4662AD555D298808059D472AF6
        │       │   ├── 04D071FB65534B4662AD555D298808059D472AF6-blob
        │       │   ├── 05E5FEED03910F671C6E6E9002A5935CEF1C8968
        │       │   ├── 05E5FEED03910F671C6E6E9002A5935CEF1C8968-blob
        │       │   ├── 09702261DC90B98C2CBB9E3240B5BB2E26969AA5
        │       │   ├── 09702261DC90B98C2CBB9E3240B5BB2E26969AA5-blob
        │       │   ├── 0FE3BC93D57490060C2CB6ECCE2503138E2502D6
        │       │   ├── 0FE3BC93D57490060C2CB6ECCE2503138E2502D6-blob
        │       │   ├── 4327F1EB711A77CDA4D038793AB12B35BCD7BC98
        │       │   ├── 4EE03997423BF0AFA5F686CAB2DBD0E6C3C5733C
        │       │   ├── 4EE03997423BF0AFA5F686CAB2DBD0E6C3C5733C-blob
        │       │   ├── 50108A1B18143539A96F849CE2A7FE070CCA3B99
        │       │   ├── 51FDD24E2A8A5F3903027FE82E0CD67DC4EC97DC
        │       │   └── 985AC8456AE13B16AF65FDE7E1D7D0F5B0CD1C5D
        │       └── SubResources
        │           └── 9A09B86CD933CE9304670C83DC4732604B02ACB6
        └── salt

13 directories, 36 files
pcfe@t7910 minigalaxy $ 
```

**Comment by sharkwouter** [comment]
This is a known issue with 0.9.2 and one of the main reasons for releasing version 0.9.3. The new version is currently available in the updates testing repo. You could try installing that: https://fedora.pkgs.org/31/fedora-updates-testing-x86_64/minigalaxy-0.9.3-1.fc31.noarch.rpm.html

**Comment by pcfe** [comment]
`sudo dnf --enablerepo updates-testing update minigalaxy` pulls in `minigalaxy-0.9.3-1.fc31.noarch` as expected.

I get further, the game downlaods and in the UI the utton changes to 'Play'.
But this is followed by

```
Executing integrity check for /home/pcfe/.cache/minigalaxy/download/Beneath a Steel Sky.sh
Verifying archive integrity... MD5 checksums are OK. All good.
Failed to start Beneath a Steel Sky:
/home/pcfe/GOG Games/BeneathaSteelSky/scummvm/scummvm_x86_64: error while loading shared libraries: /home/pcfe/GOG Games/BeneathaSteelSky/scummvm/libs/x86_64/libSDL2-2.0.so.0: file too short
```

```bash
pcfe@t7910 ~ $ ls -l ~/GOG\ Games/BeneathaSteelSky/scummvm/libs/x86_64/
total 3320
-rwxrwxrwx. 1 pcfe pcfe      21 Mar 18 22:35 libfreetype.so.6
-rw-r--r--. 1 pcfe pcfe  694800 Mar 18 22:35 libfreetype.so.6.12.1
-rwxrwxrwx. 1 pcfe pcfe      15 Mar 18 22:35 libmad.so.0
-rw-r--r--. 1 pcfe pcfe  124952 Mar 18 22:35 libmad.so.0.2.1
-rwxrwxrwx. 1 pcfe pcfe      24 Mar 18 22:35 libmpeg2convert.so.0
-rw-r--r--. 1 pcfe pcfe   30848 Mar 18 22:35 libmpeg2convert.so.0.0.0
-rwxrwxrwx. 1 pcfe pcfe      17 Mar 18 22:35 libmpeg2.so.0
-rw-r--r--. 1 pcfe pcfe  117616 Mar 18 22:35 libmpeg2.so.0.1.0
-rwxrwxrwx. 1 pcfe pcfe      15 Mar 18 22:35 libogg.so.0
-rw-r--r--. 1 pcfe pcfe   34624 Mar 18 22:35 libogg.so.0.8.2
-rwxrwxrwx. 1 pcfe pcfe      18 Mar 18 22:35 libpng12.so.0
-rw-r--r--. 1 pcfe pcfe  149904 Mar 18 22:35 libpng12.so.0.54.0
-rwxrwxrwx. 1 pcfe pcfe      20 Mar 18 22:35 libSDL2-2.0.so.0
-rw-r--r--. 1 pcfe pcfe 1111576 Mar 18 22:35 libSDL2-2.0.so.0.4.0
-rw-r--r--. 1 pcfe pcfe   55520 Mar 18 22:35 libsndio.so.6.1
-rwxrwxrwx. 1 pcfe pcfe      21 Mar 18 22:35 libtheoradec.so.1
-rw-r--r--. 1 pcfe pcfe  104688 Mar 18 22:35 libtheoradec.so.1.1.4
-rwxrwxrwx. 1 pcfe pcfe      21 Mar 18 22:35 libtheoraenc.so.1
-rw-r--r--. 1 pcfe pcfe  256360 Mar 18 22:35 libtheoraenc.so.1.1.2
-rwxrwxrwx. 1 pcfe pcfe      19 Mar 18 22:35 libtheora.so.0
-rw-r--r--. 1 pcfe pcfe  321856 Mar 18 22:35 libtheora.so.0.3.10
-rwxrwxrwx. 1 pcfe pcfe      22 Mar 18 22:35 libvorbisfile.so.3
-rw-r--r--. 1 pcfe pcfe   35216 Mar 18 22:35 libvorbisfile.so.3.3.7
-rwxrwxrwx. 1 pcfe pcfe      18 Mar 18 22:35 libvorbis.so.0
-rw-r--r--. 1 pcfe pcfe  178536 Mar 18 22:35 libvorbis.so.0.4.8
-rwxrwxrwx. 1 pcfe pcfe      13 Mar 18 22:35 libz.so.1
-rw-r--r--. 1 pcfe pcfe  104864 Mar 18 22:35 libz.so.1.2.8
```

```bash
pcfe@t7910 ~ $ cat ~/GOG\ Games/BeneathaSteelSky/scummvm/libs/x86_64/libSDL2-2.0.so.0
libSDL2-2.0.so.0.4.0
```

If I replace the text file with a symlink pointing at the named content, I get one library further, seems something went wrong when attempting to make symlinks for short libnames…

```bash
$ cd ~/GOG\ Games/BeneathaSteelSky/scummvm/libs/x86_64
$ rm libSDL2-2.0.so.0
$ ln -s libSDL2-2.0.so.0.4.0 libSDL2-2.0.so.0
```

```
Failed to start Beneath a Steel Sky:
/home/pcfe/GOG Games/BeneathaSteelSky/scummvm/scummvm_x86_64: error while loading shared libraries: /home/pcfe/GOG Games/BeneathaSteelSky/scummvm/libs/x86_64/libvorbisfile.so.3: file too short
```

**Comment by sharkwouter** [comment]
Installing scummvm should solve this. The version provided by GOG uses very old libraries which don't work on newer operating systems than Ubuntu.

**Comment by pcfe** [comment]
ah yes, thank you.

```bash
dnf install scummvm
```

can you please add a requires to the spec file?

**Comment by sharkwouter** [comment]
I think it's currently optional, maybe it should be required. I did not create the package, but the official packages also have this.

**Comment by sharkwouter** [comment]
For now I'll close this issue, since it has been fixed in the new release and I have no control over the Fedora release. If you still feel that scummvm should be a mandatory dependency, feel free to make a new issue for that.

**Comment by tim77** [comment]
Hello @pcfe. Minigalaxy in Fedora already have `scummvm` as very weak dep (`Suggests`) but if you think we should made it at least as `Recommends` please file a bug in RHBZ.
